/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlunosIndexRouteImport } from './routes/alunos.index'
import { Route as AlunosNovoRouteImport } from './routes/alunos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosNovoRoute = AlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/camera': typeof CameraRoute
  '/login': typeof LoginRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/alunos/': typeof AlunosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/camera': typeof CameraRoute
  '/login': typeof LoginRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/alunos': typeof AlunosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/camera': typeof CameraRoute
  '/login': typeof LoginRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/alunos/': typeof AlunosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admins' | '/camera' | '/login' | '/alunos/novo' | '/alunos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admins' | '/camera' | '/login' | '/alunos/novo' | '/alunos'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/camera'
    | '/login'
    | '/alunos/novo'
    | '/alunos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  CameraRoute: typeof CameraRoute
  LoginRoute: typeof LoginRoute
  AlunosNovoRoute: typeof AlunosNovoRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/novo': {
      id: '/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AlunosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  CameraRoute: CameraRoute,
  LoginRoute: LoginRoute,
  AlunosNovoRoute: AlunosNovoRoute,
  AlunosIndexRoute: AlunosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
